name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-msbuild:
    runs-on: windows-latest
    name: Run MSBuild and VSTest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        id: checkout_code
    
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.1
        id: setup_msbuild
    
      - name: Build app for release
        id: run_msbuild
        working-directory: ${{ github.workspace }}
        run: msbuild Logger.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release